# Generated by Django 4.1.4 on 2023-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_band', '0003_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
