# Generated by Django 4.1.4 on 2023-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_band', '0016_alter_album_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
