# Generated by Django 4.1.4 on 2023-01-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_band', '0017_remove_album_image_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
    ]
