# Generated by Django 4.1.4 on 2023-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_band', '0018_remove_album_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='EndUser',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
