# Generated by Django 4.1.4 on 2023-01-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_band', '0019_rename_customer_enduser_rename_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
