# Generated by Django 4.1.4 on 2023-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_band', '0020_album_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
