# Generated by Django 4.1.4 on 2023-01-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_band', '0022_image_remove_album_cover_art_delete_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
